# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KOcxX0gZfYc-22n0agSf-VkuEeu4QYi
"""


import xgboost
import joblib
import streamlit as st
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

model = joblib.load('project/mymodel2.joblib')

st.title('Will you survive if you were amoung the titanik passengares or not?')
passengerid = st.text_input('Enter your passenger ID ','1053')
pclass = st.selectbox('Enter your class',[1,2,3])
sex = st.select_slider('Choose your sex',['male','female'])
age = st.slider('Choose your age',0,100)
sibsp = st.slider('Choose your siblings number',0,10)
prach = st.slider('Choose your prach',0,10)
tiket = st.text_input('Enter your ticket number','1053')
fare = st.number_input('Enter your fare price',0,1000)
cabin = st.text_input('Enter your cabin','C52')
embark = st.select_slider('Did they embarked?',['S','C','Q'])
def predict():
  raw = np.array([passengerid,pclass,sex,age,sibsp,prach,tiket,fare,cabin,embark])
  x = pd.DataFrame([raw],columns=['PassengerId','Pclass','Sex','Age','SibSp','Parch','Ticket','Fare','Cabin','Embarked'])
  pre = model.predict(x)
  if pre[0] == 1:
    st.success('passenger survived')
  else:
    st.error('passenger died')
trigger = st.button('predict',on_click=predict)

